site_name: CS Masters Application
site_author: 'CS-Masters-Application'
copyright: '&copy; 2022 CS-Masters-Application'
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: blue
    accent: amber
  features:
    - navigation.top
    - toc.follow
    - navigation.instant
  favicon: images/logo.png
  icon:
    logo: material/school
    repo: fontawesome/brands/github
markdown_extensions:
markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
    - Home: index.md
    - 内容征集: 内容征集.md
    - 使用指南: 使用指南.md
    - 选校梯度: 选校梯度.md
$programs_list
    - 飞跃手册外部链接: 飞跃手册.md
    - CS选校之禅: CS选校之禅.md
    - 贡献者: 贡献者.md
extra:
  homepage: /选校梯度/
  social:
    - icon: fontawesome/brands/qq
      link: https://jq.qq.com/?_wv=1027&k=Ikr0DObs
    - icon: fontawesome/brands/discord
      link: https://discord.gg/HeB9QXZdFR
  analytics:
    provider: google
    property: G-MWWFQ6MJG4
repo_url: https://github.com/CS-Masters-Application/CS-Masters-Application.github.io
repo_name: CS-Masters-Application
edit_uri: edit/master/docs/
